// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: friends.proto

package friends_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FriendsServiseClient is the client API for FriendsServise service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendsServiseClient interface {
	// Add friends method
	SetFriends(ctx context.Context, in *SetFriendsIn, opts ...grpc.CallOption) (*SetFriendsOut, error)
	GetSubscription(ctx context.Context, in *GetSubscriptionIn, opts ...grpc.CallOption) (*GetSubscriptionOut, error)
	GetSubscribers(ctx context.Context, in *GetSubscribersIn, opts ...grpc.CallOption) (*GetSubscribersOut, error)
}

type friendsServiseClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendsServiseClient(cc grpc.ClientConnInterface) FriendsServiseClient {
	return &friendsServiseClient{cc}
}

func (c *friendsServiseClient) SetFriends(ctx context.Context, in *SetFriendsIn, opts ...grpc.CallOption) (*SetFriendsOut, error) {
	out := new(SetFriendsOut)
	err := c.cc.Invoke(ctx, "/FriendsServise/SetFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiseClient) GetSubscription(ctx context.Context, in *GetSubscriptionIn, opts ...grpc.CallOption) (*GetSubscriptionOut, error) {
	out := new(GetSubscriptionOut)
	err := c.cc.Invoke(ctx, "/FriendsServise/GetSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsServiseClient) GetSubscribers(ctx context.Context, in *GetSubscribersIn, opts ...grpc.CallOption) (*GetSubscribersOut, error) {
	out := new(GetSubscribersOut)
	err := c.cc.Invoke(ctx, "/FriendsServise/GetSubscribers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendsServiseServer is the server API for FriendsServise service.
// All implementations must embed UnimplementedFriendsServiseServer
// for forward compatibility
type FriendsServiseServer interface {
	// Add friends method
	SetFriends(context.Context, *SetFriendsIn) (*SetFriendsOut, error)
	GetSubscription(context.Context, *GetSubscriptionIn) (*GetSubscriptionOut, error)
	GetSubscribers(context.Context, *GetSubscribersIn) (*GetSubscribersOut, error)
	mustEmbedUnimplementedFriendsServiseServer()
}

// UnimplementedFriendsServiseServer must be embedded to have forward compatible implementations.
type UnimplementedFriendsServiseServer struct {
}

func (UnimplementedFriendsServiseServer) SetFriends(context.Context, *SetFriendsIn) (*SetFriendsOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFriends not implemented")
}
func (UnimplementedFriendsServiseServer) GetSubscription(context.Context, *GetSubscriptionIn) (*GetSubscriptionOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedFriendsServiseServer) GetSubscribers(context.Context, *GetSubscribersIn) (*GetSubscribersOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscribers not implemented")
}
func (UnimplementedFriendsServiseServer) mustEmbedUnimplementedFriendsServiseServer() {}

// UnsafeFriendsServiseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendsServiseServer will
// result in compilation errors.
type UnsafeFriendsServiseServer interface {
	mustEmbedUnimplementedFriendsServiseServer()
}

func RegisterFriendsServiseServer(s grpc.ServiceRegistrar, srv FriendsServiseServer) {
	s.RegisterService(&FriendsServise_ServiceDesc, srv)
}

func _FriendsServise_SetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFriendsIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiseServer).SetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FriendsServise/SetFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiseServer).SetFriends(ctx, req.(*SetFriendsIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsServise_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiseServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FriendsServise/GetSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiseServer).GetSubscription(ctx, req.(*GetSubscriptionIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendsServise_GetSubscribers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscribersIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServiseServer).GetSubscribers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FriendsServise/GetSubscribers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServiseServer).GetSubscribers(ctx, req.(*GetSubscribersIn))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendsServise_ServiceDesc is the grpc.ServiceDesc for FriendsServise service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendsServise_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FriendsServise",
	HandlerType: (*FriendsServiseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetFriends",
			Handler:    _FriendsServise_SetFriends_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _FriendsServise_GetSubscription_Handler,
		},
		{
			MethodName: "GetSubscribers",
			Handler:    _FriendsServise_GetSubscribers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friends.proto",
}
