// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: friends.proto

package friends_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data for add peer_1 and peer_2
type SetFriendsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Peer_1 id
	Peer_1 string `protobuf:"bytes,1,opt,name=peer_1,json=peer1,proto3" json:"peer_1,omitempty"`
	// Peer_2 id
	Peer_2 string `protobuf:"bytes,2,opt,name=peer_2,json=peer2,proto3" json:"peer_2,omitempty"`
}

func (x *SetFriendsIn) Reset() {
	*x = SetFriendsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friends_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFriendsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendsIn) ProtoMessage() {}

func (x *SetFriendsIn) ProtoReflect() protoreflect.Message {
	mi := &file_friends_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendsIn.ProtoReflect.Descriptor instead.
func (*SetFriendsIn) Descriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{0}
}

func (x *SetFriendsIn) GetPeer_1() string {
	if x != nil {
		return x.Peer_1
	}
	return ""
}

func (x *SetFriendsIn) GetPeer_2() string {
	if x != nil {
		return x.Peer_2
	}
	return ""
}

// Response add friend
type SetFriendsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Result of the operation
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetFriendsOut) Reset() {
	*x = SetFriendsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friends_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFriendsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendsOut) ProtoMessage() {}

func (x *SetFriendsOut) ProtoReflect() protoreflect.Message {
	mi := &file_friends_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendsOut.ProtoReflect.Descriptor instead.
func (*SetFriendsOut) Descriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{1}
}

func (x *SetFriendsOut) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_friends_proto protoreflect.FileDescriptor

var file_friends_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3c, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x49, 0x6e, 0x12,
	0x15, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x65, 0x65, 0x72, 0x31, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x32, 0x22, 0x29, 0x0a,
	0x0d, 0x53, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x3f, 0x0a, 0x0e, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x53, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x0d, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x49, 0x6e, 0x1a, 0x0e, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_friends_proto_rawDescOnce sync.Once
	file_friends_proto_rawDescData = file_friends_proto_rawDesc
)

func file_friends_proto_rawDescGZIP() []byte {
	file_friends_proto_rawDescOnce.Do(func() {
		file_friends_proto_rawDescData = protoimpl.X.CompressGZIP(file_friends_proto_rawDescData)
	})
	return file_friends_proto_rawDescData
}

var file_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_friends_proto_goTypes = []interface{}{
	(*SetFriendsIn)(nil),  // 0: SetFriendsIn
	(*SetFriendsOut)(nil), // 1: SetFriendsOut
}
var file_friends_proto_depIdxs = []int32{
	0, // 0: FriendsServise.SetFriends:input_type -> SetFriendsIn
	1, // 1: FriendsServise.SetFriends:output_type -> SetFriendsOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_friends_proto_init() }
func file_friends_proto_init() {
	if File_friends_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_friends_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFriendsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friends_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFriendsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friends_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friends_proto_goTypes,
		DependencyIndexes: file_friends_proto_depIdxs,
		MessageInfos:      file_friends_proto_msgTypes,
	}.Build()
	File_friends_proto = out.File
	file_friends_proto_rawDesc = nil
	file_friends_proto_goTypes = nil
	file_friends_proto_depIdxs = nil
}
